networks:
  mongonetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.55.0/24
          gateway: 192.168.55.1

services: 
  mongodb-one:
    container_name: mongodb-one
    image: mongo:latest
    volumes:
      - ./scripts/replica-set-init.js:/scripts/replica-set-init.js
    networks:
      mongonetwork:
        ipv4_address: 192.168.55.10
    ports:
      - "27027:27017"
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "banking_set" ]
  
  mongodb-two:
    container_name: mongodb-two
    image: mongo:latest
    networks:
      mongonetwork:
        ipv4_address: 192.168.55.11
    ports:
      - "27028:27017"
    depends_on:
      - mongodb-one
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "banking_set" ]
  
  mongodb-three:
    container_name: mongodb-three
    image: mongo:latest
    networks:
      mongonetwork:
        ipv4_address: 192.168.55.12
    ports:
      - "27029:27017"
    depends_on:
      - mongodb-one      
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "banking_set" ]
